### ISSUE TITLE
Is there an easy way to remove the start time and end time?

### ISSUE THREAD

**Issue by mikr0smile** [buildix/timex#21]
### Discussed in https://github.com/buildix/timex/discussions/20

<div type='discussions-op-text'>

<sup>Originally posted by **mohan-nishit** December 14, 2022</sup>
Hello, 

The plugin looks spectacular! 
I have a use case around an employee leave calendar, where start and end times are not needed. Is there an easy way to remove this from the plugin? Or is it a part of your future roadmap?</div>

**Comment by mikrosmile** [comment]
Implemented on latest release v.1.1.5
