### ISSUE TITLE
Error When Install On Laravel 10.3.3

### ISSUE THREAD

**Issue by arpaulustindi** [buildix/timex#32]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - buildix/timex[1.0.1, ..., 1.1.6] require illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires buildix/timex * -> satisfiable by buildix/timex[1.0.1, ..., 1.1.6].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require buildix/timex:*" to figure out if any version is installable, or "composer require buildix/timex:^2.1" if you know which you need.

**Comment by yamakrane** [comment]
same here, this is turning me crazy. did you find any fix ?

**Comment by yamakrane** [comment]
@arpaulustindi any fix ?

**Comment by HeartlandTechie** [comment]
Ditto . . . Laravel 10 doesn't work so I pulled it back to 9 and it installed fine.  I suspect it just needs some composer tweaks on what version it's happy with

**Comment by yamakrane** [comment]
@HeartlandTechie this is really not the way you should do it

**Comment by HeartlandTechie** [comment]
> @HeartlandTechie this is really not the way you should do it

Well @yamakrane, when you want to evaluate a piece of software and decide it's viability before stressing over what needs to be done to get it functional . . . yes it is the way you should do it.

**Comment by mikrosmile** [comment]
Fixed by v.1.1.7

**Comment by arpaulustindi** [comment]
Thank you
