### ISSUE TITLE
Navigation Label

### ISSUE THREAD

**Issue by MarJose123** [buildix/timex#8]
make this not dependent on a date as label name, as make the user decide what will they want to name it as for example the user can named it as `Calendar` instead of `Thursday, 24 Nov`

https://github.com/buildix/timex/blob/2390274dc77e230a97c48a774060b77a0b7055fd/config/timex.php#L71

**Comment by mikrosmile** [comment]
Will provide an option

**Comment by mikrosmile** [comment]
Added option in #12
