### ISSUE TITLE
Declaration of Buildix\Timex\Pages\Timex::getHeading() error while installing

### ISSUE THREAD

**Issue by PepijnVDK1** [buildix/timex#9]
When installing this package I get the following error:

` Declaration of Buildix\Timex\Pages\Timex::getHeading(): Illuminate\Contracts\Support\Htmlable|string must be compatible with Filament\Pages\Page::getHeading(): string

  at vendor/buildix/timex/src/Pages/Timex.php:74
     70▕     {
     71▕         return config('timex.pages.shouldRegisterNavigation');
     72▕     }
     73▕ 
  ➜  74▕     protected function getHeading(): string|Htmlable
     75▕     {
     76▕         return " ";
     77▕     }
     78▕ `

I might be doing something wrong, I wonder if there is a solution

**Comment by PepijnVDK1** [comment]
This issue can be deleted, I had to update my filament package...

My apologies!!

**Comment by mikrosmile** [comment]
Thanks for reply. Was intended to question same thing about filament
